language: java
jdk:
- openjdk11
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: project-books
    token:
      secure: "**************************"
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
env:
  global:
  - secure: djMbWesx8rDY81mgKCQCkDXANb9VBaAeNHZYO5pKj4NySewkatw70ph7m5ZFAZ09wFNYPz/vtMP8I6nRWBZ+wXfTurvKNK8fwort5Jc8dnIbLNXx/Y1nThD++pt/pKjrExjE1QJRWpgIwBjH9ipfEYv+cut+9m84rX/sire5+V1NlAfiXEvwuN/1W9Eb2D7QureiHTPaaDl9ze/Pt6q8JDeORMzUEF+WxHmJqiAppC3dPUbmYf/nYkla7RorurCl/opsWB/8L33ZQn5+lRqUaklzbilxx/PQ1rjdG1C5yt4F7GnpPDlfmeigv5EC6UoRjHLgWu9z7JXNyJf6d9sNjObDITu6cQalXxcEAO0VkamxvLR4Z/uMk7IXG8Z0/w0jacUcCu63pgdOXrIylGSPL8b9fcQGq9+fEc7+AAi6VAvyyU3VuF4Kk+EtDlcyBWOAs2v5rKTg/7KLsVHHltsUpKORHy7x+wjbHLdH7xIcw1i8H6/lM32hYVCV8DRFSFy5pgLZ/NcvsdlZI29zyt1iMrB2AbfpgBlqlvJdYAG/w0r6jGqGZpyAlsOAvnfJ3dUR8g16MMOYT1MXzuZoeUl6a/FB84eBZ06cM94t6WwGKgxezeaXDIgWirbKDFMTfMMvfFFup7naMHn9fPjxYvWPwoYN/udJ8zrtKkPfwzLWcvs=
