language: java
jdk:
  - openjdk11
  - oraclejdk11
cache:
  directories:
    - $HOME/.m2
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
after_success:
  - bash <(curl -s https://codecov.io/bash)